//
// Created by jujun on 10/20/2020.
//

#ifndef PROJECT_1_DOUBLY_LINKED_LIST_JONATHAN_SMITH113_LINKEDLISTEXCEPTION_H
#define PROJECT_1_DOUBLY_LINKED_LIST_JONATHAN_SMITH113_LINKEDLISTEXCEPTION_H

using namespace std;

class LinkedListException{};
#endif //PROJECT_1_DOUBLY_LINKED_LIST_JONATHAN_SMITH113_LINKEDLISTEXCEPTION_H
